Add hydrogen-dihydrogen zero-copy conversion for sequential tensors
LLNL/DiHydrogen pull request #110
Opened 2023-12-14 17:13 UTC by benson31

I also added a few utilities for convenience.

2023-12-19 01:43 UTC, ndryden requested changes
Some minor changes, but the core looks very good.

2023-12-19 01:43 UTC, ndryden commented on include/h2/tensor/fixed_size_tuple.hpp
> +template <typename T, typename SizeType, SizeType N>
Please add documentation.

Also, I'm not sure whether this name is the best, until I read the code I wasn't sure whether it was for initialization or getting a prefix.

2023-12-19 01:43 UTC, ndryden commented on include/h2/tensor/fixed_size_tuple.hpp
> +  if (in.size() > 0UL)
Is this check needed? We already know `in.size() != 0` from the above check, and it can't be negative, so it should always be safe to do the subtraction.

(It occurs to me that technically `SizeType` could be signed, but (1) that's silly (so someone will probably do it); (2) if you have a negative size you deserve what you're getting.)

2023-12-19 01:43 UTC, ndryden commented on include/h2/tensor/fixed_size_tuple.hpp
> +  if (in.size() == 0)
```suggestion
  if (in.empty())
```

2023-12-19 01:43 UTC, ndryden commented on include/h2/tensor/fixed_size_tuple.hpp
> +  if (in.size() == 0UL)
```suggestion
  if (in.empty())
```

2023-12-19 01:43 UTC, ndryden commented on include/h2/utils/As.hpp
> +To as(From const& x)
This can be `constexpr`.

2023-12-19 01:43 UTC, ndryden commented on include/h2/utils/As.hpp
> +To safe_as(From const& x)
I believe this can be `constexpr` as well, since we would only throw when things fail.

2023-12-19 01:43 UTC, ndryden commented on test/unit_test/utils/unit_test_as.cpp
> +    SECTION("Floating point")
For funsies: Can we check +/- 0, infs, and NaNs?

2023-12-19 01:43 UTC, ndryden commented on include/h2/tensor/hydrogen_interop.hpp
> +        auto const nelems = safe_as<h_size_type>(tensor.shape(0));
```suggestion
        auto const nelems = safe_as<h_size_type>(tensor.numel());
```

2023-12-20 19:45 UTC, benson31 commented on include/h2/tensor/fixed_size_tuple.hpp
> +template <typename T, typename SizeType, SizeType N>
I have added a docstring. I have not renamed it. Suggestions for a reasonable name?

2023-12-20 19:46 UTC, benson31 commented on test/unit_test/utils/unit_test_as.cpp
> +    SECTION("Floating point")
Done

2023-12-20 19:48 UTC, ndryden commented on include/h2/tensor/fixed_size_tuple.hpp
> +template <typename T, typename SizeType, SizeType N>
I don't have a better idea right now, so let's leave it and fix it later.

2023-12-20 19:48 UTC, ndryden approved these changes

2023-12-20 20:04 UTC, merged